config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'contact' => 'static_pages#contact'
  get 'faq' => 'static_pages#faq'
  get 'about' => 'static_pages#about'
  get 'privacy' => 'static_pages#privacy'
  get 'safety' => 'static_pages#safety'
  get 'terms' => 'static_pages#terms'

  get 'thankyou_ping' => 'static_pages#thankyou_ping'
  get 'thankyou_logout' => 'static_pages#thankyou_logout'
  get 'thankyou_contract' => 'static_pages#thankyou_contract'

  get 'give_or_get_help' => 'static_pages#give_or_get_help'

  get 'signup' => 'users#new'
  get 'profile_page_1' => 'users#edit'
  get 'profile_page_2' => 'users#edit_2'
  get 'profile_page_3' => 'users#edit_3'
  get 'my_profile' => 'users#show'
  get 'my_projects' => 'users#my_projects'
  get 'edit_my_profile' => 'users#edit_my_profile'
  get 'delete_my_profile' => 'users#delete_my_profile'
  get 'my_bank' => 'users#my_bank'
  get 'my_notifications' => 'users#my_notifications'
  get 'my_system_notifications' => 'users#my_system_notifications'
  get 'my_offers_to_help' => 'users#my_offers_to_help'
  get 'my_requests_for_help' => 'users#my_offers_to_help'
  get 'my_reviews' => 'users#my_reviews'
  get 'account_settings' => 'users#account_settings'
  resources :users

  get 'login' => 'sessions#new'

  get 'get_help_gallery' => 'get_help#index'
  get 'get_help_new_project' => 'get_help#new'
  get 'get_help_show_project' => 'get_help#show'
  get 'get_help_edit_project' => 'get_help#edit'
  get 'get_help_archive_project' => 'get_help#archive'

  get 'give_help_gallery' => 'give_help#index'
  get 'give_help_new_project' => 'give_help#new'
  get 'give_help_show_project' => 'give_help#show'
  get 'give_help_edit_project' => 'give_help#edit'
  get 'give_help_archive_project' => 'give_help#archive'

  get 'project_1' => 'fake_projects#project_1'
  get 'project_2' => 'fake_projects#project_2'
  get 'project_3' => 'fake_projects#project_3'
  get 'project_4' => 'fake_projects#project_4'
  get 'project_5' => 'fake_projects#project_5'
  get 'project_6' => 'fake_projects#project_6'
  get 'project_messages' => 'fake_projects#project_messages'
  get 'project_contract' => 'fake_projects#project_contract'
  get 'project_signed' => 'fake_projects#project_signed'
  get 'submit_review' => 'fake_projects#submit_review'
  get 'gallery' => 'fake_projects#gallery'

  get 'profile_1' => 'fake_users#profile_1'
  get 'profile_2' => 'fake_users#profile_2'
  get 'profile_3' => 'fake_users#profile_3'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fake_projects_controller.rb
class FakeProjectsController < ApplicationController

	def project_1
	end

	def project_2
	end

	def project_3
	end

	def project_4
	end

	def project_5
	end

	def project_6
	end

	def project_messages
	end

	def project_contract
	end

	def project_signed
	end

	def submit_review
	end

	def gallery
	end
	
end

app/controllers/fake_users_controller.rb
class FakeUsersController < ApplicationController

	def profile_1
	end

	def profile_2
	end

	def profile_3
	end
	
end

app/controllers/get_help_controller.rb
class GetHelpController < ApplicationController

	attr_accessor :name, :category, :sub_category, :description, :hours, :additional_information

	def index
	end
	
	def new
		@get_help_project = "placeholder"
	end

	def show
	end

	def edit
		@get_help_project = "placeholder"
	end

	def archive
	end

private

	def get_help_project_params
		params.require(:get_help_project).permit(:name, :category, :sub_category, :description, :hours, :additional_information)
	end
	
end

app/controllers/give_help_controller.rb
class GiveHelpController < ApplicationController

	attr_accessor :name, :category, :sub_category, :description, :hours, :additional_information

	def index
	end

	def new
		@give_help_project = "placeholder"
	end

	def show
	end

	def edit
		@give_help_project = "placeholder"
	end

	def archive
	end

private

	def give_help_project_params
		params.require(:give_help_project).permit(:name, :category, :sub_category, :description, :hours, :additional_information)
	end
	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
			redirect_back_or user
		else
			flash.now[:danger] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end
	
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def home
	end

	def contact
	end

	def faq
	end

	def about
	end

	def privacy
	end

	def safety
	end

	def terms
	end

	def thankyou_ping
	end

	def thankyou_logout
	end

	def thankyou_contract
	end

	def give_or_get_help
	end

	def account_settings
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	# Only logged in users can edit or update user profiles
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
	before_action :correct_user, only: [:edit, :update]
	attr_accessor :name, :email, :password, :zipcode

	def index
		# @users = User.all
	end

	def show
		# @user = User.find(params[:id])
	end

	def new
		# @user = User.new
		@user = "placeholder"
	end

	def create
		# @user = User.new(user_params)
		# if @user.save
		# 	log_in @user
		# 	redirect_to @user
		# else
		# 	render 'new'
		# end
	end

	def edit
		# @user = User.find(params[:id])
		@user = "placeholder"
	end

	def edit_2
	end

	def edit_3
	end

	def update
		# @user = User.find(params[:id])
		# if @user.update_attributes(user_params)
		# 	flash[:success] = "Profile Updated"
		# 	redirect_to @user
		# else
		# 	render 'edit'
		# end
	end

	def my_projects
	end

	def edit_my_profile
		@user = 'placeholder'
	end

	def delete_my_profile
	end

	def my_bank
	end

	def my_notifications
	end

	def my_system_notifications
	end

	def my_offers_to_help
	end

	def my_requests_for_help
	end

	def my_reviews
	end

	def destroy
		# User.find(params[:id]).destroy
		# flash[:success] = "User deleted"
		# redirect_to users_url
	end

private

	def user_params
		params.require(:user).permit(:name, :email, :password, :zipcode)
	end

	# Before filters

	# Confirms a logged-in user
	def logged_in_user
		# unless logged_in?
		# 	store_location
		# 	flash[:danger] = "Please Log In"
		# 	redirect_to login_url
		# end
	end

	# Confirms the correct user
	def correct_user
		# @user = User.find(params[:id])
		# redirect_to(root_url) unless @user == current_user?(@user)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return the full title on a per-page basis
	def full_title(page_title = '')
		base_title = "TimeSwappers"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	end
end

app/helpers/fake_projects_helper.rb
module FakeProjectsHelper
end

app/helpers/fake_users_helper.rb
module FakeUsersHelper
end

app/helpers/get_help_helper.rb
module GetHelpHelper
end

app/helpers/give_help_helper.rb
module GiveHelpHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	#Log in the user
	def log_in(user)
		session[:user_id] = user_id
	end

	#Remembers a user in a persistent session
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	#Return true if the given user is the current user
	def current_user?(user)
		user == current_user
	end

	#Return the current logged-in user
	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	#Return true if the user is logged in, false otherwise
	def logged_in?
		!current_user.nil?
	end

	#Log out the current user
	def log_out
		session.delete(:user_id)
		@current_user = nil
	end

	#Redirect to stored location (or to the default)
	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	#Store the URL trying to be accessed
	def store_location
		session[:forwarding_url] = request.url if request.get?
	end

	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fake_users/profile_3.html.erb
profile_3.html.erb

app/views/layouts/_account_navigation.html.erb
<div class="row">
	<div class="col-md-12">
		<!-- Fixed navbar -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to "TimeSwappers", root_path, class: "navbar-brand" %>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<li role="presentation"><a href="#">Help</a></li>
						<li><hr /></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Messages<span class="caret"></span></a>
          					<ul class="dropdown-menu">
								<li><%= link_to my_system_notifications_path do %>
									Notifications 
									<span class="badge">0</span>
									<% end %>
								</li>
								<li><%= link_to my_notifications_path do %>
									Messages
									<span class="badge">2</span>
									<% end %>
								</li>
							</ul>
						</li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Rachelle<span class="caret"></span></a>
          					<ul class="dropdown-menu">
          						<li><%= link_to "Project Gallery", gallery_path %></li>
								<li><%= link_to "My Offers to Help", my_offers_to_help_path %></li>
								<li><%= link_to "My Requests for Help", my_requests_for_help_path %></li>
								<li><%= link_to "My Time Bank", my_bank_path %></li>
								<li><%= link_to "Reviews", my_reviews_path %></li>
								<li><%= link_to "Profile", edit_my_profile_path %></li>
								<li><%= link_to "Account Settings", account_settings_path %></li>
								<li role="presentation"><%= link_to "Log Out", thankyou_logout_path %></li>
							</ul>
						</li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
	<div class="col-md-12">
		<!-- Fixed footer -->
		<footer class="navbar navbar-default navbar-static-bottom" id="footer">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-footer">
						<li><%= link_to 'Contact', contact_path %></li>
						<li><%= link_to 'FAQ', faq_path %></li>
						<li><%= link_to 'About', about_path %></li>
						<li><%= link_to 'Privacy Policy', privacy_path %></li>
						<li class="footer-nav"><%= link_to 'Safety & Community Guidelines', safety_path %></li>
						<li class="footer-nav"><%= link_to 'Terms of Service', terms_path %></li>
					</ul>
					<ul class="nav navbar-nav navbar-footer">
						<li class="footer-nav"><a href="https://www.facebook.com/timeswappers/" target="_blank"><%= image_tag("social-icons/facebook.png", class: "social") %></a></li>
						<li class="footer-nav"><a href="https://twitter.com/TimeSwappers" target="_blank"><%= image_tag("social-icons/twitter.png", class: "social") %></a></li>
						<li class="footer-nav"><a href="https://www.youtube.com/channel/UCoRiHvWxjIgEPr8tkdQ6t0g" target="_blank"><%= image_tag("social-icons/youtube.png", class: "social") %></a></li>
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</footer>
	</div>
</div>

app/views/layouts/_old-account-nav.html.erb
<div class="sidebar">
	<nav role="navigation">
		<ul class="nav nav-sidebar">
			<li role="presentation"><%= link_to "Project Gallery", gallery_path %></a></li>
			<li><hr /></li>
			<li role="presentation"><%= link_to my_notifications_path do %>
				Notifications
				<span class="badge">2</span>
				<% end %>
			</li>
			<li role="presentation"><%= link_to "My Projects", my_projects_path %><li>
			<li role="presentation"><%= link_to "My Time Bank", my_bank_path %></li>
			<li><hr /></li>
			<li role="presentation"><%= link_to "My Profile", my_profile_path %></li>
			<li role="presentation"><%= link_to "Edit My Profile", edit_my_profile_path %></li>
			<li role="presentation"><%= link_to "Delete My Profile", delete_my_profile_path %></li>
		</ul>
	</nav>
</div>

app/views/static_pages/thankyou_logout.html.erb
<% provide(:title, 'Thank You') %>

<%= render 'layouts/header' %>

<div class="container-static">
	<div class="container">
		<h1>Thank You</h1>
		<p>You have successfully logged out.</p>
	</div>
</div>

app/views/users/edit_2.html.erb
<% provide(:title, 'Complete Your Profile') %>

<%= render 'layouts/header' %>

<div class="container-static">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Complete Your Profile</h1>
				<div class="progress">
					<div class="progress-bar progress-bar-success" style="width: 50%">
						Contact Information & Photo
					</div>
					<div class="progress-bar progress-bar-success" style="width: 50%">
						Choose What You Have A Knack For
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<h3>Choose How You Can Help Other TimeSwappers</h3>
				<p>Select at least one, or as many as you want</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Clean and Tidy" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div>
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="General Cleaning" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Laundry" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Getting Organized" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Lawn & Garden" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Car, Truck, & Boat Cleaning" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Helping Hand" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div><!-- /input-group -->

				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Handyman & Simple Repairs" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Errands & Driving" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Painting" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Furniture Assembly" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Heavy Lifting" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Beauty and Fitness" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div><!-- /input-group -->
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Fitness" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Hair Styling" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Massage" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Spa Services" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>
	
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Tutoring and Teaching" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div><!-- /input-group -->
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="How-To" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Instruction" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Academic Tutoring" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Business Services" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div><!-- /input-group -->
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Web Design & Graphics" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Computers & Tech" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Writing & Research" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Sales & Marketing" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Accounting & Bookkeeping" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="input-group project-list">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="Party & Entertainment" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div><!-- /input-group -->
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-11">
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Cooking & Baking" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Waitstaff" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Entertainment" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
						<div class="input-group project-list">
							<span class="input-group-addon">
								<input type="checkbox" aria-label="...">
							</span>
							<input type="text" value="Photography" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6 col-md-offset-3 center">
				<br />
				<span class="list-group">
					<input type="checkbox" aria-label="...">   By checking this box, I acknowledge that I have read and agree to the TimeSwappers <%= link_to "Privacy Policy", privacy_path %>, <%= link_to "Terms of Use", terms_path %> and <%= link_to "Safety & Security Guidelines", safety_path %>.</input>
				</span>
				<hr />
				<div class="center-button">
					<%= link_to "Continue", give_or_get_help_path, class: "btn btn-lg btn-primary" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/edit_3.html.erb
<% provide(:title, 'Complete Your Profile') %>

<%= render 'layouts/header' %>

<div class="container-static">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Complete Your Profile</h1>
				<p>Fill out at least one service you want to buy and one service you want to sell in order to complete your profile.<p>
				<div class="progress">
					<div class="progress-bar progress-bar-success" style="width: 33.333%">
						Contact Information & Photo
					</div>
					<div class="progress-bar progress-bar-success" style="width: 33.333%">
						What You Want to Buy & Sell
					</div>
					<div class="progress-bar progress-bar-success" style="width: 33.333%">
						Your Safety & Privacy
					</div>
				</div>
				<p>The information that you enter will not been saved in any way. You may simply hit submit to move forward.</p>

				<hr />

				<h3><%= link_to "SAFETY & COMMUNITY GUIDELINES", safety_path %></h3>
				<p>Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</p>

				<hr />

				<h3><%= link_to "PRIVACY POLICY", privacy_path %></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</p>

				<hr />

				<h3><%= link_to "TERMS OF SERVICE", terms_path %></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean euismod bibendum laoreet. Proin gravida dolor sit amet lacus accumsan et viverra justo commodo. Proin sodales pulvinar tempor. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam fermentum, nulla luctus pharetra vulputate, felis tellus mollis orci, sed rhoncus sapien nunc eget odio.</p>

				<hr >

				<div class="input-group">
					<span class="input-group-addon">
						<input type="checkbox" aria-label="...">
					</span>
					<input type="text" value="I agree to the Safety and Community Guidelines, the Privacy Policy, and the Terms of Service" class="form-control" id="basic-url" aria-describedby="basic-addon3" readonly>
				</div>

				<br />
				
				<div class="center-button">
					<%= link_to "Continue", give_or_get_help_path, class: "btn btn-lg btn-primary" %>
				</div>
			</div>
		</div>
	</div>
</div>